-- =====================================================================
-- VinaBook — Product catalog refresh (data only)
-- Replaces the 56 placeholder rows (product_id 3..58) with a realistic,
-- balanced Vietnamese bookstore catalog.
--
-- SCHEMA UNCHANGED: only UPDATE statements on existing rows, so all
-- foreign keys (order_details, rates, carts) stay intact.
-- Images are intentionally NOT touched (existing URLs are kept).
--
-- Categories (live `book` DB):
--   1 Sach Chinh tri - Phap luat   2 Sach Khoa hoc cong nghe - Kinh te
--   3 Sach Van hoc nghe thuat      4 Sach Van hoa xa hoi - Lich su
--   5 Sach Giao trinh              6 Sach Truyen, tieu thuyet
--   7 Sach Tam ly, tam linh, ton giao   8 Sach thieu nhi   9 Sach Van hoc
-- =====================================================================

SET NAMES utf8mb4;
START TRANSACTION;

-- ---------- 1. Sách Chính trị – Pháp luật (6) ----------
UPDATE products SET category_id=1, name='Hiến Pháp Nước Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam (Hiện Hành)', author='Quốc Hội Việt Nam', price=45000, discount=0, sold=28, quantity=150, entered_date='2025-09-10', status=1, description='Toàn văn Hiến pháp hiện hành của nước CHXHCN Việt Nam — văn bản pháp lý cao nhất, nền tảng cho toàn bộ hệ thống pháp luật quốc gia. Ấn bản chuẩn, tiện tra cứu.' WHERE product_id=3;
UPDATE products SET category_id=1, name='Luật Doanh Nghiệp (Hiện Hành)', author='Quốc Hội Việt Nam', price=78000, discount=5, sold=22, quantity=120, entered_date='2025-10-02', status=1, description='Trọn bộ quy định mới nhất về thành lập, tổ chức quản lý và hoạt động của doanh nghiệp tại Việt Nam. Tài liệu không thể thiếu cho người khởi nghiệp và nhà quản lý.' WHERE product_id=4;
UPDATE products SET category_id=1, name='Luật Lao Động Thực Hành', author='Nguyễn Văn Phần', price=92000, discount=10, sold=18, quantity=100, entered_date='2025-11-15', status=1, description='Phân tích và hướng dẫn áp dụng Bộ luật Lao động qua các tình huống thực tế: hợp đồng, tiền lương, kỷ luật, tranh chấp. Dành cho cả người lao động lẫn người sử dụng lao động.' WHERE product_id=5;
UPDATE products SET category_id=1, name='Cẩm Nang Pháp Lý Cho Doanh Nghiệp', author='Trương Thanh Đức', price=135000, discount=15, sold=41, quantity=90, entered_date='2026-01-20', status=1, description='Sổ tay pháp lý toàn diện giúp doanh nghiệp phòng ngừa rủi ro: hợp đồng, thuế, sở hữu trí tuệ, giải quyết tranh chấp. Viết bởi luật sư giàu kinh nghiệm thực chiến.' WHERE product_id=6;
UPDATE products SET category_id=1, name='Luật Đất Đai Và Văn Bản Hướng Dẫn Thi Hành', author='Bộ Tư Pháp', price=110000, discount=0, sold=12, quantity=80, entered_date='2025-08-05', status=1, description='Tập hợp đầy đủ Luật Đất đai cùng các nghị định, thông tư hướng dẫn thi hành mới nhất. Công cụ tra cứu thiết yếu cho công tác quản lý và giao dịch bất động sản.' WHERE product_id=7;
UPDATE products SET category_id=1, name='Tìm Hiểu Bộ Luật Dân Sự Việt Nam', author='Đỗ Văn Đại', price=156000, discount=8, sold=15, quantity=85, entered_date='2026-02-11', status=1, description='Bình luận khoa học về Bộ luật Dân sự — quyền sở hữu, hợp đồng, thừa kế, bồi thường thiệt hại. Giúp bạn đọc nắm vững nguyên tắc nền tảng của luật tư.' WHERE product_id=8;

-- ---------- 2. Sách Khoa học công nghệ – Kinh tế (8) ----------
UPDATE products SET category_id=2, name='Clean Code - Mã Sạch Và Cách Viết', author='Robert C. Martin', price=168000, discount=10, sold=86, quantity=140, entered_date='2026-03-01', status=1, description='Cẩm nang kinh điển của Uncle Bob về cách viết mã nguồn sạch, dễ đọc, dễ bảo trì. Bắt buộc đọc với mọi lập trình viên muốn nâng tầm tay nghề.' WHERE product_id=9;
UPDATE products SET category_id=2, name='The Pragmatic Programmer - Lập Trình Viên Thực Dụng', author='Andrew Hunt & David Thomas', price=175000, discount=12, sold=58, quantity=110, entered_date='2026-03-18', status=1, description='Những bài học thực dụng đưa bạn từ thợ code thành kỹ sư phần mềm bậc thầy: tư duy, công cụ, thói quen nghề nghiệp bền vững.' WHERE product_id=16;
UPDATE products SET category_id=2, name='AI Cơ Bản - Trí Tuệ Nhân Tạo Cho Mọi Người', author='Phạm Huy Hoàng', price=132000, discount=5, sold=45, quantity=120, entered_date='2026-04-02', status=1, description='Giải thích trí tuệ nhân tạo, machine learning và deep learning bằng ngôn ngữ dễ hiểu, không nặng toán. Khởi đầu hoàn hảo cho người mới bước vào lĩnh vực AI.' WHERE product_id=17;
UPDATE products SET category_id=2, name='Blockchain Fundamentals - Nền Tảng Công Nghệ Chuỗi Khối', author='Don Tapscott', price=145000, discount=8, sold=31, quantity=95, entered_date='2026-02-22', status=1, description='Khám phá cách blockchain định hình lại tài chính, kinh doanh và xã hội. Từ Bitcoin đến hợp đồng thông minh, một bức tranh toàn cảnh về cuộc cách mạng chuỗi khối.' WHERE product_id=18;
UPDATE products SET category_id=2, name='Khởi Nghiệp Tinh Gọn (The Lean Startup)', author='Eric Ries', price=128000, discount=15, sold=72, quantity=130, entered_date='2026-03-25', status=1, description='Phương pháp xây dựng startup hiện đại: thử nghiệm nhanh, học hỏi từ khách hàng, xoay trục đúng lúc. Kim chỉ nam cho mọi nhà sáng lập.' WHERE product_id=19;
UPDATE products SET category_id=2, name='Từ Tốt Đến Vĩ Đại (Good to Great)', author='Jim Collins', price=138000, discount=20, sold=74, quantity=125, entered_date='2026-03-05', status=1, description='Nghiên cứu vì sao một số công ty bứt phá từ tốt lên vĩ đại trong khi số khác thì không. Những nguyên lý lãnh đạo và quản trị đã được kiểm chứng bằng dữ liệu.' WHERE product_id=42;
UPDATE products SET category_id=2, name='Nhà Đầu Tư Thông Minh', author='Benjamin Graham', price=198000, discount=10, sold=55, quantity=100, entered_date='2026-02-26', status=1, description='Kinh thánh của đầu tư giá trị, cuốn sách gối đầu giường của Warren Buffett. Tư duy kỷ luật giúp bạn đầu tư an toàn và sinh lời bền vững.' WHERE product_id=43;
UPDATE products SET category_id=2, name='Kinh Tế Học Hài Hước (Freakonomics)', author='Steven D. Levitt & Stephen J. Dubner', price=142000, discount=12, sold=39, quantity=105, entered_date='2026-02-20', status=1, description='Góc nhìn kinh tế học bất ngờ và dí dỏm về những câu hỏi đời thường. Khám phá mặt ẩn giấu của mọi thứ qua dữ liệu và lý lẽ sắc bén.' WHERE product_id=47;

-- ---------- 3. Sách Văn học nghệ thuật (7) ----------
UPDATE products SET category_id=3, name='Truyện Kiều', author='Nguyễn Du', price=68000, discount=5, sold=52, quantity=130, entered_date='2025-09-09', status=1, description='Kiệt tác thi ca của đại thi hào Nguyễn Du — 3254 câu lục bát kể về cuộc đời nàng Kiều. Đỉnh cao của văn học cổ điển Việt Nam, di sản của muôn đời.' WHERE product_id=10;
UPDATE products SET category_id=3, name='Số Đỏ', author='Vũ Trọng Phụng', price=72000, discount=0, sold=33, quantity=100, entered_date='2025-10-19', status=1, description='Tiểu thuyết trào phúng bậc thầy về Xuân Tóc Đỏ và xã hội thành thị nhố nhăng thời thuộc địa. Tiếng cười sắc bén phê phán thói rởm đời, học làm sang.' WHERE product_id=11;
UPDATE products SET category_id=3, name='Vang Bóng Một Thời', author='Nguyễn Tuân', price=78000, discount=0, sold=20, quantity=90, entered_date='2025-12-01', status=1, description='Tập truyện ngắn tài hoa tái hiện vẻ đẹp của một thời đã xa: thú uống trà, chơi chữ, những con người cuối mùa nho nhã. Văn phong Nguyễn Tuân độc đáo, đậm chất nghệ sĩ.' WHERE product_id=12;
UPDATE products SET category_id=3, name='Dế Mèn Phiêu Lưu Ký', author='Tô Hoài', price=56000, discount=10, sold=64, quantity=160, entered_date='2026-02-14', status=1, description='Cuộc phiêu lưu của chú Dế Mèn qua thế giới loài vật — bài học về lòng dũng cảm, tình bạn và khát vọng. Tác phẩm gối đầu giường của bao thế hệ thiếu nhi Việt Nam.' WHERE product_id=13;
UPDATE products SET category_id=3, name='Chí Phèo', author='Nam Cao', price=55000, discount=10, sold=50, quantity=120, entered_date='2025-09-28', status=1, description='Truyện ngắn hiện thực đỉnh cao về bi kịch bị tha hóa của người nông dân. Tiếng kêu Ai cho tao lương thiện vang vọng mãi trong văn học Việt Nam.' WHERE product_id=39;
UPDATE products SET category_id=3, name='Tắt Đèn', author='Ngô Tất Tố', price=60000, discount=8, sold=30, quantity=95, entered_date='2025-11-06', status=1, description='Bức tranh chân thực về số phận người nông dân dưới ách sưu thuế qua hình tượng chị Dậu. Một bản án đanh thép với xã hội thực dân phong kiến.' WHERE product_id=40;
UPDATE products SET category_id=3, name='Những Người Khốn Khổ', author='Victor Hugo', price=218000, discount=15, sold=41, quantity=85, entered_date='2026-01-12', status=1, description='Đại tiểu thuyết về Jean Valjean và hành trình cứu rỗi giữa nước Pháp đầy biến động. Bản hùng ca bất hủ về lòng nhân ái, công lý và phẩm giá con người.' WHERE product_id=41;

-- ---------- 4. Sách Văn hóa xã hội – Lịch sử (6) ----------
UPDATE products SET category_id=4, name='Việt Nam Sử Lược', author='Trần Trọng Kim', price=125000, discount=5, sold=47, quantity=110, entered_date='2025-11-03', status=1, description='Bộ thông sử Việt Nam bằng chữ quốc ngữ đầu tiên, trình bày mạch lạc dòng chảy lịch sử dân tộc từ thời dựng nước đến cận đại. Công trình kinh điển của học giả Trần Trọng Kim.' WHERE product_id=14;
UPDATE products SET category_id=4, name='Lịch Sử Thế Giới Hiện Đại', author='Nguyễn Anh Thái', price=158000, discount=8, sold=24, quantity=90, entered_date='2026-01-08', status=1, description='Tổng quan các biến cố lớn định hình thế giới hiện đại: hai cuộc thế chiến, chiến tranh lạnh, toàn cầu hóa. Tài liệu nền tảng cho người yêu lịch sử.' WHERE product_id=15;
UPDATE products SET category_id=4, name='Đại Việt Sử Ký Toàn Thư', author='Ngô Sĩ Liên', price=245000, discount=12, sold=19, quantity=70, entered_date='2025-08-22', status=1, description='Bộ quốc sử đồ sộ ghi chép lịch sử Đại Việt từ thời Hồng Bàng đến nhà Lê. Di sản sử học vô giá, nguồn tư liệu gốc cho mọi nghiên cứu về Việt Nam xưa.' WHERE product_id=24;
UPDATE products SET category_id=4, name='Súng, Vi Trùng Và Thép', author='Jared Diamond', price=189000, discount=15, sold=35, quantity=95, entered_date='2026-02-05', status=1, description='Tác phẩm đoạt giải Pulitzer lý giải vì sao các nền văn minh phát triển không đồng đều. Một cái nhìn liên ngành chấn động về số phận của các xã hội loài người.' WHERE product_id=25;
UPDATE products SET category_id=4, name='Homo Deus: Lược Sử Tương Lai', author='Yuval Noah Harari', price=195000, discount=12, sold=43, quantity=100, entered_date='2026-03-14', status=1, description='Phần tiếp nối của Sapiens, khám phá tương lai loài người trong kỷ nguyên công nghệ sinh học và trí tuệ nhân tạo. Những câu hỏi lớn về vận mệnh nhân loại.' WHERE product_id=46;
UPDATE products SET category_id=4, name='Sapiens: Lược Sử Loài Người', author='Yuval Noah Harari', price=189000, discount=15, sold=145, quantity=180, entered_date='2026-06-05', status=1, description='Hành trình 70.000 năm của loài người từ vượn người đến chúa tể địa cầu. Cuốn sách bán chạy toàn cầu thay đổi cách ta nhìn nhận về chính mình và lịch sử.' WHERE product_id=56;

-- ---------- 5. Sách Giáo trình (6) ----------
UPDATE products SET category_id=5, name='Giáo Trình Cấu Trúc Dữ Liệu Và Giải Thuật', author='Đinh Mạnh Tường', price=88000, discount=5, sold=38, quantity=130, entered_date='2025-09-15', status=1, description='Giáo trình nền tảng về cấu trúc dữ liệu và thuật toán: danh sách, cây, đồ thị, sắp xếp, tìm kiếm. Kèm ví dụ minh họa cho sinh viên công nghệ thông tin.' WHERE product_id=20;
UPDATE products SET category_id=5, name='Giáo Trình Mạng Máy Tính', author='Nguyễn Thúc Hải', price=95000, discount=0, sold=26, quantity=110, entered_date='2025-10-27', status=1, description='Kiến thức cơ bản đến nâng cao về mạng máy tính: mô hình OSI, TCP/IP, định tuyến, bảo mật. Tài liệu chuẩn cho học phần mạng tại các trường đại học.' WHERE product_id=21;
UPDATE products SET category_id=5, name='Giáo Trình Lập Trình Java', author='Trần Đình Quế', price=102000, discount=10, sold=44, quantity=140, entered_date='2026-01-30', status=1, description='Học lập trình Java từ căn bản: cú pháp, hướng đối tượng, collection, xử lý ngoại lệ, lập trình giao diện. Bài tập phong phú bám sát chương trình đào tạo.' WHERE product_id=22;
UPDATE products SET category_id=5, name='Giáo Trình Cơ Sở Dữ Liệu', author='Phạm Thị Anh Lê', price=98000, discount=8, sold=29, quantity=115, entered_date='2025-12-12', status=1, description='Nền tảng về mô hình quan hệ, thiết kế CSDL, chuẩn hóa và ngôn ngữ SQL. Giáo trình cốt lõi cho sinh viên ngành công nghệ thông tin và hệ thống thông tin.' WHERE product_id=23;
UPDATE products SET category_id=5, name='Giáo Trình Nhập Môn Trí Tuệ Nhân Tạo', author='Đinh Mạnh Tường', price=112000, discount=8, sold=22, quantity=100, entered_date='2026-01-18', status=1, description='Giới thiệu các khái niệm cốt lõi của trí tuệ nhân tạo: tìm kiếm, biểu diễn tri thức, suy diễn, học máy. Cầu nối lý thuyết và ứng dụng cho sinh viên.' WHERE product_id=44;
UPDATE products SET category_id=5, name='Giáo Trình Kinh Tế Vi Mô', author='Nguyễn Văn Công', price=99000, discount=5, sold=31, quantity=120, entered_date='2025-12-05', status=1, description='Các nguyên lý cung cầu, hành vi người tiêu dùng, lý thuyết sản xuất và cấu trúc thị trường. Giáo trình chuẩn cho khối ngành kinh tế và quản trị kinh doanh.' WHERE product_id=45;

-- ---------- 6. Sách Truyện, tiểu thuyết (8) ----------
UPDATE products SET category_id=6, name='Sherlock Holmes Toàn Tập - Tập 1', author='Arthur Conan Doyle', price=215000, discount=10, sold=51, quantity=110, entered_date='2026-01-15', status=1, description='Những vụ án ly kỳ của thám tử lừng danh phố Baker. Tài suy luận thiên tài của Sherlock Holmes đã làm say mê độc giả khắp thế giới hơn một thế kỷ qua.' WHERE product_id=26;
UPDATE products SET category_id=6, name='Bố Già (The Godfather)', author='Mario Puzo', price=145000, discount=8, sold=49, quantity=100, entered_date='2025-11-20', status=1, description='Kiệt tác về gia đình mafia Corleone — quyền lực, danh dự và máu. Một bức chân dung sắc lạnh về thế giới ngầm và bản chất con người. Tiểu thuyết bất hủ.' WHERE product_id=27;
UPDATE products SET category_id=6, name='Không Gia Đình', author='Hector Malot', price=132000, discount=5, sold=27, quantity=95, entered_date='2025-10-08', status=1, description='Hành trình của cậu bé Rémi lưu lạc khắp nước Pháp đi tìm gia đình. Câu chuyện cảm động về nghị lực, lòng nhân hậu và khát khao yêu thương.' WHERE product_id=28;
UPDATE products SET category_id=6, name='Cây Cam Ngọt Của Tôi', author='José Mauro de Vasconcelos', price=108000, discount=12, sold=68, quantity=130, entered_date='2026-03-10', status=1, description='Câu chuyện trong veo mà đau đáu về cậu bé Zezé nghèo khó và trí tưởng tượng diệu kỳ. Một cuốn sách lay động trái tim hàng triệu độc giả toàn cầu.' WHERE product_id=29;
UPDATE products SET category_id=6, name='Suối Nguồn (The Fountainhead)', author='Ayn Rand', price=232000, discount=15, sold=33, quantity=85, entered_date='2026-02-28', status=1, description='Tiểu thuyết tư tưởng về kiến trúc sư Howard Roark và cuộc chiến bảo vệ chính kiến trước đám đông. Bản tuyên ngôn về chủ nghĩa cá nhân và sự sáng tạo.' WHERE product_id=30;
UPDATE products SET category_id=6, name='Harry Potter Và Hòn Đá Phù Thủy', author='J.K. Rowling', price=135000, discount=12, sold=120, quantity=200, entered_date='2026-05-20', status=1, description='Khởi đầu của loạt truyện phù thủy huyền thoại. Cậu bé Harry bước vào trường Hogwarts và khám phá thế giới phép thuật kỳ diệu. Hiện tượng xuất bản toàn cầu.' WHERE product_id=52;
UPDATE products SET category_id=6, name='Đắc Nhân Tâm', author='Dale Carnegie', price=86000, discount=18, sold=156, quantity=220, entered_date='2026-06-08', status=1, description='Cuốn sách về nghệ thuật đối nhân xử thế bán chạy nhất mọi thời đại. Những nguyên tắc vàng giúp bạn chinh phục lòng người và thành công trong giao tiếp.' WHERE product_id=57;
UPDATE products SET category_id=6, name='Nhà Giả Kim', author='Paulo Coelho', price=79000, discount=20, sold=168, quantity=230, entered_date='2026-06-10', status=1, description='Hành trình của cậu chăn cừu Santiago đi tìm kho báu và khám phá vận mệnh đời mình. Câu chuyện truyền cảm hứng được dịch ra hơn 80 thứ tiếng.' WHERE product_id=58;

-- ---------- 7. Sách Tâm lý, tâm linh, tôn giáo (6) ----------
UPDATE products SET category_id=7, name='Sức Mạnh Tiềm Thức', author='Joseph Murphy', price=110000, discount=10, sold=63, quantity=140, entered_date='2026-01-22', status=1, description='Khám phá nguồn sức mạnh vô tận ẩn trong tiềm thức và cách khai mở nó để thay đổi cuộc đời. Một trong những cuốn sách phát triển bản thân có ảnh hưởng nhất.' WHERE product_id=31;
UPDATE products SET category_id=7, name='Quẳng Gánh Lo Đi Và Vui Sống', author='Dale Carnegie', price=98000, discount=8, sold=57, quantity=130, entered_date='2025-12-18', status=1, description='Những phương pháp thiết thực để vượt qua lo âu, tìm lại bình an và sống trọn vẹn từng ngày. Kim chỉ nam cho một tâm hồn an nhiên giữa cuộc sống bộn bề.' WHERE product_id=32;
UPDATE products SET category_id=7, name='Hành Trình Về Phương Đông', author='Baird T. Spalding', price=105000, discount=5, sold=42, quantity=110, entered_date='2025-11-11', status=1, description='Ghi chép về cuộc gặp gỡ các bậc hiền triết phương Đông và những huyền bí của tâm linh. Bản dịch của Nguyên Phong đưa người đọc vào thế giới minh triết sâu thẳm.' WHERE product_id=33;
UPDATE products SET category_id=7, name='Đường Xưa Mây Trắng', author='Thích Nhất Hạnh', price=165000, discount=12, sold=38, quantity=100, entered_date='2026-02-09', status=1, description='Kể lại cuộc đời Đức Phật bằng giọng văn dung dị, thấm đẫm chất thơ và thiền vị. Một tác phẩm chạm đến trái tim của hàng triệu người trên khắp thế giới.' WHERE product_id=34;
UPDATE products SET category_id=7, name='Muôn Kiếp Nhân Sinh', author='Nguyên Phong', price=168000, discount=8, sold=112, quantity=190, entered_date='2026-06-01', status=1, description='Những câu chuyện về luân hồi, nhân quả và hành trình của linh hồn qua muôn kiếp. Tác phẩm tâm linh ăn khách bậc nhất, gợi mở suy ngẫm về lẽ sống.' WHERE product_id=54;
UPDATE products SET category_id=7, name='Tư Duy Nhanh Và Chậm', author='Daniel Kahneman', price=178000, discount=15, sold=134, quantity=200, entered_date='2026-06-03', status=1, description='Công trình tâm lý học đoạt giải Nobel về hai hệ thống tư duy chi phối mọi quyết định của con người. Cuốn sách thay đổi cách bạn hiểu về lý trí và sai lầm.' WHERE product_id=55;

-- ---------- 8. Sách thiếu nhi (6) ----------
UPDATE products SET category_id=8, name='Kho Tàng Truyện Cổ Tích Việt Nam', author='Nguyễn Đổng Chi', price=135000, discount=10, sold=44, quantity=150, entered_date='2025-10-30', status=1, description='Tuyển tập đồ sộ những câu chuyện cổ tích dân gian Việt Nam: Tấm Cám, Thạch Sanh, Cây tre trăm đốt... Gìn giữ hồn cốt văn hóa dân tộc cho thế hệ nhỏ.' WHERE product_id=35;
UPDATE products SET category_id=8, name='10 Vạn Câu Hỏi Vì Sao', author='Nhiều Tác Giả', price=89000, discount=15, sold=71, quantity=170, entered_date='2026-01-05', status=1, description='Bộ sách khoa học giải đáp hàng nghìn thắc mắc của trẻ về thế giới quanh ta: thiên nhiên, vũ trụ, cơ thể, công nghệ. Nuôi dưỡng trí tò mò và niềm yêu khám phá.' WHERE product_id=36;
UPDATE products SET category_id=8, name='Hoàng Tử Bé', author='Antoine de Saint-Exupéry', price=76000, discount=8, sold=59, quantity=160, entered_date='2025-12-25', status=1, description='Câu chuyện trong trẻo và sâu sắc về cậu hoàng tử nhỏ đến từ tiểu hành tinh B612. Tác phẩm văn học được yêu thích nhất nước Pháp, dành cho mọi lứa tuổi.' WHERE product_id=37;
UPDATE products SET category_id=8, name='Totto-chan Bên Cửa Sổ', author='Kuroyanagi Tetsuko', price=92000, discount=10, sold=46, quantity=140, entered_date='2026-02-17', status=1, description='Hồi ức cảm động về cô bé Totto-chan và ngôi trường Tomoe đặc biệt. Một quan niệm giáo dục đầy nhân văn khiến cả trẻ em lẫn người lớn yêu thích.' WHERE product_id=38;
UPDATE products SET category_id=8, name='Thám Tử Lừng Danh Conan - Tập 1', author='Gosho Aoyama', price=25000, discount=5, sold=78, quantity=250, entered_date='2026-03-22', status=1, description='Thám tử Shinichi bị teo nhỏ thành cậu bé Conan và bắt đầu phá những vụ án hóc búa. Bộ truyện tranh trinh thám ăn khách bậc nhất mọi thời đại.' WHERE product_id=48;
UPDATE products SET category_id=8, name='Doraemon - Tập 1', author='Fujiko F. Fujio', price=22000, discount=10, sold=105, quantity=300, entered_date='2026-05-12', status=1, description='Chú mèo máy Doraemon từ tương lai cùng những bảo bối thần kỳ và cậu bạn Nobita. Bộ truyện tranh tuổi thơ thân thương của bao thế hệ thiếu nhi.' WHERE product_id=51;

-- ---------- 9. Sách Văn học (3) ----------
UPDATE products SET category_id=9, name='Tôi Thấy Hoa Vàng Trên Cỏ Xanh', author='Nguyễn Nhật Ánh', price=88000, discount=10, sold=67, quantity=160, entered_date='2026-02-15', status=1, description='Câu chuyện tuổi thơ trong trẻo nơi làng quê nghèo với tình anh em, tình bạn và những rung động đầu đời. Tác phẩm best-seller của Nguyễn Nhật Ánh đã lên màn ảnh.' WHERE product_id=49;
UPDATE products SET category_id=9, name='Cho Tôi Xin Một Vé Đi Tuổi Thơ', author='Nguyễn Nhật Ánh', price=78000, discount=8, sold=58, quantity=150, entered_date='2026-01-26', status=1, description='Tấm vé đưa người đọc trở về thế giới hồn nhiên của tuổi thơ với bao trò nghịch ngợm đáng yêu. Cuốn sách gối đầu giường của cả trẻ em và người lớn.' WHERE product_id=50;
UPDATE products SET category_id=9, name='Mắt Biếc', author='Nguyễn Nhật Ánh', price=95000, discount=10, sold=98, quantity=180, entered_date='2026-05-28', status=1, description='Chuyện tình day dứt của Ngạn dành cho Hà Lan từ làng Đo Đo đến phố thị. Một trong những tác phẩm lãng mạn được yêu thích nhất của Nguyễn Nhật Ánh.' WHERE product_id=53;

COMMIT;

-- ---------- Verification ----------
SELECT c.category_id, c.category_name, COUNT(p.product_id) AS so_luong
FROM categories c LEFT JOIN products p ON p.category_id = c.category_id
GROUP BY c.category_id, c.category_name ORDER BY c.category_id;
